Allow reverse proxies
CatoTH/antragsgruen pull request #800
Opened 2023-05-23 23:20 UTC by tiran133

This change fixes a bug when the app is running on "http" and is deployed behind a reverse proxy running on "https" 

It fails in the url comparison since the https != http which is used in $_SERVER['REQUEST_SCHEME'].

$_SERVER['HTTP_X_FORWARDED_PROTO']  takes precedent over  $_SERVER['REQUEST_SCHEME']

2023-05-24 16:42 UTC, CatoTH commented
@tiran133 Did you check if this fixes your issue? Is it related to logging out?
You're probably using this in combination with a plugin? The method in question is only used from a SAML-Plugin as far as I see...

2023-05-24 22:00 UTC, tiran133 commented
Hi,

yes you are right it is related to logging out in relation with the SAML-Plugin. And yes, it fixes the problem.

I am developing a new saml plugin for a client and took the gruene_de_saml as stating point. Everything worked great except the logout. (Its working now).

That's when I found the error.

Although after I did the pull request I realized there is another place it should be changed within the config/web.php
related to secure cookies. 

At this point it might be just easier for me to set "REQUEST_SCHEME" to https in the nginx config.
Which solves the whole thing without code changes.

As you mention the function is only used in relation to the saml plugin. So I could just remove that function as well.

Lots of options I guess.

So not sure what you want to do. 

Its up to you its your project.

Kind regards

2023-05-25 00:49 UTC, Rotzbua requested changes
All variables `$_SERVER['HTTP_***']` are not save to use. They are the headers sent by the client. Not sanitized they can be abused for an injection attack.

2023-05-25 01:04 UTC, tiran133 commented
Well that's not entirely true. It always depends for what you use it for. Yes its user input and should be treated with caution but It can be safe or unsafe it depends.

I would not output it to the page or store it in the database without further sanitizing it. But in an if statement?

You see the code please let us know what your attack payload will be to exploit it. In this particular case?

Also the $_SERVER['HTTP_***'] is used a few times in this project. That does not make it attack able or unsafe!

Kind regards

2023-05-26 17:12 UTC, CatoTH commented
Yea I'm fine with it. The only injection-related danger related to what @Rotzbua mentioned I see is that in case of later refactoring when one didn't pay attention about this issue and used `$scheme` for anything else than comparing it. But in a `getSubdomain`-method, that should be too hypothentical.

2023-05-26 17:12 UTC, merged